### ISSUE TITLE
After upgrading to 3.5.1: "FATAL: Unable to load template: Cannot find module 'doc/.JSDoc.template/publish'"

### ISSUE THREAD

**Issue by lll000111** [jsdoc3/jsdoc#1399]
It all worked until the upgrade of the jsdoc version. Of course there is a file `doc/.JSDoc.template/publish.js`.  My `jsdoc.json` config file has an option `"template": "doc/JSDoc.template"`. What changed? Nothing on _my_ side that's for sure, I've been running the jsdoc comment several times every day.

My previous JSDoc version was 3.4.3.

**EDIT**

I thought maybe the default template changed. Removing my custom template configuration option (I changed some CSS from the previous default template) and using the "built-in" default template worked. Then I did this:

    cp -a node_modules/jsdoc/templates/default/ doc/JSDoc.template

and added the configuration option back in. Again I get the same error - now with the pristine default template. So it can't have been the changes to the template (I noticed the new default template differs from the one I copied some time ago).

**Comment by lll000111** [comment]
**PROBLEM FOUND**

It cannot deal with relative paths any more!

The problem is the path will be different for each system/developer working with the repository, I **need** relative paths.

**Comment by sven-piller** [comment]
I had the same problem. Please try 

      "./doc/JSDoc.template"
       ^^

This helped me. Seems to be the same as https://github.com/jsdoc3/jsdoc/issues/1394

**Comment by lll000111** [comment]
@sven-piller So I wanted to say "I tried that" (I did, not five minutes ago) - but I just tried again and this time it worked, five minutes ago it didn't.....
