### ISSUE TITLE
Markdown plugin not working in 3.4.2.

### ISSUE THREAD

**Issue by NicolasPelletier** [jsdoc3/jsdoc#1279]
With the release of 3.4.2 can this error when I run jsDoc:

```
15:00:49-pelletn~/Proj1/projectNameHere (master *>)$ ./node_modules/.bin/jsdoc -c ./doc-template/jsdoc.conf.json
module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/pelletn/Proj1/projectNameHere/plugins/markdown'
    at Function.Module._resolveFilename (module.js:325:15)
    at Requizzle.requizzle (/Users/pelletn/Proj1/projectNameHere/node_modules/jsdoc/node_modules/requizzle/lib/requizzle.js:87:22)
    at infectProxy (/Users/pelletn/Proj1/projectNameHere/node_modules/jsdoc/node_modules/requizzle/lib/loader.js:82:28)
    at Module.targetModule.require (/Users/pelletn/Proj1/projectNameHere/node_modules/jsdoc/node_modules/requizzle/lib/loader.js:101:11)
    at require (internal/module.js:12:17)
    at Object.exports.installPlugins (/Users/pelletn/Proj1/projectNameHere/node_modules/jsdoc/lib/jsdoc/plugins.js:23:18)
    at Object.module.exports.cli.createParser (/Users/pelletn/Proj1/projectNameHere/node_modules/jsdoc/cli.js:340:17)
    at module.exports.cli.main (/Users/pelletn/Proj1/projectNameHere/node_modules/jsdoc/cli.js:225:20)
    at Object.module.exports.cli.runCommand (/Users/pelletn/Proj1/projectNameHere/node_modules/jsdoc/cli.js:180:5)
    at /Users/pelletn/Proj1/projectNameHere/node_modules/jsdoc/jsdoc.js:103:9
    at Object.<anonymous> (/Users/pelletn/Proj1/projectNameHere/node_modules/jsdoc/jsdoc.js:104:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
15:00:51-pelletn~/Proj1/projectNameHere (master *>)$
```

My config file is:

```
{
  "source": {
    "include": [ "doc-template/readme.md", "src/" ],
    "exclude": [],
    "includePattern": ".+\\.js(doc)?$",
    "excludePattern": "(^|\\/|\\\\)_"
  },
  "plugins": [],
  "opts": {
    "pedantic": true,
    "verbose": true,
    "recurse": true,
    "destination": "./doc/"
  },
  "plugins": [ "plugins/markdown" ],
  "markdown": {
    "parser"   : "gfm",
    "hardwrap" : true,
    "idIdHeadings": true,
    "excludeTags": [ "fileoverview" ]
  },
  "templates": {
    "cleverLinks": false,
    "monospaceLinks": false,
    "default": {
      "includeDate": true,
      "useLongnameInNav": true,
      "outputSourceFiles": true
    },
    "systemName": "Autodesk",
    "footer": "",
    "navType": "vertical",
    "theme": "cerulean"
  },
  "tags": {
    "allowUnknownTags": false,
    "dictionaries": ["closure", "jsdoc"]
  }
}
```

Everything works as expected with jsDoc 3.4.1

I use:
- Node 4.5
- npm 2.15.9

I run on Mac OSX 10.11.6

**Comment by NicolasPelletier** [comment]
In the root of my project, we have a `plugins` folder and it seems it tries to load `markdown` from there now.

**Comment by hegemonic** [comment]
Should be fixed in JSDoc 3.4.3.

**Comment by bordigoni** [comment]
Hello,
This issue seem to be present in 3.4.3.

It fails in lib/jsdoc/plugin.js when you do `require(plugin[i])` it is like current path is not in node_modules/jsdoc. I wondered if maybe that is more of a Node.js issue (I'm running on 6.5.0) but i thinks it is before because plugin path at that point is an absolute path (/Users/.../my-proj/plugins/markdown.

**Comment by polonel** [comment]
Confirmed this is still not fixed when having a 'plugins' folder in the root of the project.

**Comment by hegemonic** [comment]
Sorry, I misremembered whether this was fixed or not.

I believe this issue is a duplicate of #1081.

**Comment by robwalch** [comment]
Sorry, but I'm trying to setup jsdoc in a project. I'd like to output markdown docs instead of html docs. I've created config that includes the markdown plugin and options as follows:
```json
{
  "source": {
    "include": [
      "./src/js/main.js",
    ]
  },
  "opts": {
    "debug": true,
    "destination": "docs/api",
    "readme": "docs/README.md"
  },
  "plugins": ["plugins/markdown"],
  "markdown": {
    "idIdHeadings": true
  }
}
```
There is no difference in output with these options. The plugin still seems to be broken. This is what the output looks like:
```
DEBUG: JSDoc 3.4.3 (Thu, 10 Nov 2016 00:25:10 GMT)
DEBUG: Environment info: {"env":{"conf":{"tags":{"allowUnknownTags":true,"dictionaries":["jsdoc","closure"]},"templates":{"monospaceLinks":false,"cleverLinks":false},"source":{"includePattern":".+\\.js(doc|x)?$","excludePattern":"","include":["./src/js/jwplayer.js","./src/js/api/api.js"]},"plugins":["./plugins/markdown"],"opts":{"debug":true,"destination":"docs/api","readme":"./docs/README.md"},"markdown":{"idIdHeadings":true,"tags":["deprecated"]}},"opts":{"_":[],"configure":"docs/jsdoc.conf.json","debug":true,"destination":"docs/api","readme":"./docs/README.md","encoding":"utf8"}}}
DEBUG: Parsing source files: ["/Users/rwalch/dev/jwplayer/src/js/jwplayer.js","/Users/rwalch/dev/jwplayer/src/js/api/api.js"]
Parsing /Users/rwalch/dev/jwplayer/src/js/jwplayer.js ...
Parsing /Users/rwalch/dev/jwplayer/src/js/api/api.js ...
DEBUG: Finished parsing source files.
DEBUG: Indexing doclets...
DEBUG: Adding inherited symbols, mixins, and interface implementations...
DEBUG: Adding borrowed doclets...
DEBUG: Post-processing complete.
Generating output files...
Finished running in 0.65 seconds.
```
I've pulled down some other projects with similar configs and ran their commands. Same thing - html docs. Am I missing something?

**Comment by hegemonic** [comment]
@robwalch, the Markdown plugin is for handling comments in Markdown format, not for generating output files in Markdown format. You might want to try [jsdoc-to-markdown](https://github.com/jsdoc2md/jsdoc-to-markdown).
