### ISSUE TITLE
Issues with loading plugins and template resources

### ISSUE THREAD

**Issue by vitaly-t** [jsdoc3/jsdoc#1394]
After updating from jsDoc 3.4 to 3.5, started getting `requizzle` - related issues:

```
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:485:15)
    at Requizzle.requizzle (D:\NodeJS\pg-promise\node_modules\requizzle\lib\requizzle.js:87:22)
    at infectProxy (D:\NodeJS\pg-promise\node_modules\requizzle\lib\loader.js:82:28)
    at Module.targetModule.require (D:\NodeJS\pg-promise\node_modules\requizzle\lib\loader.js:101:11)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\NodeJS\pg-promise\node_modules\jsdoc\lib\jsdoc\name.js:7:9)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at Object.load (D:\NodeJS\pg-promise\node_modules\requizzle\lib\loader.js:112:15)
```

**Comment by vitaly-t** [comment]
**UPDATE**

Ok, I deleted all the dependencies and reinstall afresh, now getting a new error:

```
Error: Cannot find module 'D:\NodeJS\pg-promise\node_modules\jsdoc\shortLinks'
    at Function.Module._resolveFilename (module.js:485:15)
    at Requizzle.requizzle (D:\NodeJS\pg-promise\node_modules\requizzle\lib\requizzle.js:87:22)
    at infectProxy (D:\NodeJS\pg-promise\node_modules\requizzle\lib\loader.js:82:28)
    at Module.targetModule.require (D:\NodeJS\pg-promise\node_modules\requizzle\lib\loader.js:101:11)
    at require (internal/module.js:11:18)
```

In my `jsdoc.json` I have:

```js
  "plugins": [
    "plugins/markdown",
    "jsdoc/shortLinks"
  ]
```
 And I have file `shortLinks.js` in the same folder as `jsdoc.json`.

It all worked perfectly in jsDoc 3.4, but doesn't work in v3.5

**Comment by vitaly-t** [comment]
I have been able to fix the issue by replacing each local relative path with a new one:

Original:

```
layoutFile: './jsdoc/layout.html',

plugins: [
  'jsdoc/shortLinks'
]
```
replaced with:

```
layoutFile: '../../jsdoc/layout.html',

plugins: [
  '../../jsdoc/shortLinks'
]
```

Something in v3.5 that stops it from finding the local files.

**Comment by vitaly-t** [comment]
Just found another issue - Externals are not generated at all.

**Comment by hegemonic** [comment]
Please file a new issue for the problem with externals.

Regarding the layout file and plugin issues: There was a change in JSDoc 3.5.0 to the way that we load these resources. Previously we searched for them relative to the config file, then relative to the current directory; we now search the other way around. That said, it sounds like the current behavior is wrong. I'll investigate.

**Comment by hegemonic** [comment]
I think I've figured out the basic problem: `path.getResourcePath` assumes that if the requested directory exists, then the requested file exists, too. This doesn't really make any sense. (And I say that as the person who wrote this stupid code!)

It'll be hard to change this behavior, because we allow people to omit the `.js` extension from JavaScript files, just like `require()` does. You can specify things like `plugins/markdown` when you really mean `plugins/markdown.js`. I guess we can try searching for the requested file both with and without a `.js` extension (and then as a directory?); that seems kind of messy, but it might be our only option.

Man, I really hate dealing with file paths.

**Comment by vitaly-t** [comment]
On a good note, when I changed it simply to the following, it worked both in v3.4 and v3.5:

```js
layoutFile: './jsdoc/layout.html',

plugins: [
  './jsdoc/shortLinks'
]
```

This one seems perfectly ok to me now :wink:

**Comment by hegemonic** [comment]
That's definitely good news! I'm still going to fix `path.getResourcePath`, though.

**Comment by hegemonic** [comment]
Okay, I took a stab at fixing this issue, and the fix is on master and releases/3.5. It'll be included in JSDoc 3.5.2.

I completely rewrote the existing code, so I'm sure things are now broken in some new and exciting way. I look forward to the inevitable bug reports!
